### ISSUE TITLE
1.13.2 : Missing generateChunckData method.

### ISSUE THREAD

**Issue by DF1229** [chaseoes/VoidWorld#5]
Generating a world using this generator in minecraft 1.13.2 returned an error. 
Multiverse-Core version: 4.0.0-b766
VoidWorld version: 1.0
Spigot version: git-Spigot-1a3504a-84f3da3 (MC: 1.13.2) API v1.13.2-R0.1-SNAPSHOT

Below is the error.
```
>mvc voidworld normal -g VoidWorld
[11:27:31 INFO]: CONSOLE: Starting creation of world 'voidworld'...
[11:27:31 INFO]: [Multiverse-Core] Loading World & Settings - 'voidworld' - Env: NORMAL - Type: NORM
[11:27:31 WARN]: net.minecraft.server.v1_13_R2.ReportedException: Exception generating new chunk
[11:27:31 WARN]:        at net.minecraft.server.v1_13_R2.ChunkProviderServer.a(ChunkProviderServer.j
[11:27:31 WARN]:        at net.minecraft.server.v1_13_R2.ChunkProviderServer.getChunkAt(ChunkProvide
[11:27:31 WARN]:        at net.minecraft.server.v1_13_R2.World.getChunkAt(World.java:267)
[11:27:31 WARN]:        at net.minecraft.server.v1_13_R2.World.getChunkAtWorldCoords(World.java:263)
[11:27:31 WARN]:        at net.minecraft.server.v1_13_R2.World.getType(World.java:658)
[11:27:31 WARN]:        at org.bukkit.craftbukkit.v1_13_R2.block.CraftBlock.getType(CraftBlock.java:
[11:27:31 WARN]:        at com.onarandombox.MultiverseCore.utils.SimpleBlockSafety.playerCanSpawnHer
[11:27:31 WARN]:        at com.onarandombox.MultiverseCore.MVWorld.readSpawnFromWorld(MVWorld.java:4
[11:27:31 WARN]:        at com.onarandombox.MultiverseCore.MVWorld.<init>(MVWorld.java:82)
[11:27:31 WARN]:        at com.onarandombox.MultiverseCore.MVWorld.<init>(MVWorld.java:59)
[11:27:31 WARN]:        at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.ja
[11:27:31 WARN]:        at com.onarandombox.MultiverseCore.utils.WorldManager.addWorld(WorldManager.
[11:27:31 WARN]:        at com.onarandombox.MultiverseCore.commands.CreateCommand.runCommand(CreateC
[11:27:31 WARN]:        at com.onarandombox.commandhandler.CommandHandler.checkAndRunCommand(Command
[11:27:31 WARN]:        at com.onarandombox.commandhandler.CommandHandler.processFoundCommands(Comma
[11:27:31 WARN]:        at com.onarandombox.commandhandler.CommandHandler.locateAndRunCommand(Comman
[11:27:31 WARN]:        at com.onarandombox.MultiverseCore.MultiverseCore.onCommand(MultiverseCore.j
[11:27:31 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46)
[11:27:31 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[11:27:31 WARN]:        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.j
[11:27:31 WARN]:        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchServerCommand(CraftSe
[11:27:31 WARN]:        at net.minecraft.server.v1_13_R2.DedicatedServer.handleCommandQueue(Dedicate
[11:27:31 WARN]:        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:418)
[11:27:31 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831)
[11:27:31 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:72
[11:27:31 WARN]:        at java.lang.Thread.run(Thread.java:748)
[11:27:31 WARN]: Caused by: java.util.concurrent.CompletionException: java.lang.UnsupportedOperation
[11:27:31 WARN]:        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.
[11:27:31 WARN]:        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFutur
[11:27:31 WARN]:        at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:60
[11:27:31 WARN]:        at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture
[11:27:31 WARN]:        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.j
[11:27:31 WARN]:        at com.google.common.util.concurrent.MoreExecutors$DirectExecutorService.exe
[11:27:31 WARN]:        at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFut
[11:27:31 WARN]:        at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:59
[11:27:31 WARN]:        at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture
[11:27:31 WARN]:        at java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.ja
[11:27:31 WARN]:        at java.util.concurrent.CompletableFuture.thenApplyAsync(CompletableFuture.j
[11:27:31 WARN]:        at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:147)
[11:27:31 WARN]:        at java.util.Map.computeIfAbsent(Map.java:957)
[11:27:31 WARN]:        at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:137)
[11:27:31 WARN]:        at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:143)
[11:27:31 WARN]:        at net.minecraft.server.v1_13_R2.ChunkStatus.a(SourceFile:105)
[11:27:31 WARN]:        at net.minecraft.server.v1_13_R2.ChunkStatus.a(SourceFile:22)
[11:27:31 WARN]:        at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:143)
[11:27:31 WARN]:        at java.util.Map.computeIfAbsent(Map.java:957)
[11:27:31 WARN]:        at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:137)
[11:27:31 WARN]:        at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:143)
[11:27:31 WARN]:        at net.minecraft.server.v1_13_R2.ChunkStatus.a(SourceFile:105)
[11:27:31 WARN]:        at net.minecraft.server.v1_13_R2.ChunkStatus.a(SourceFile:22)
[11:27:31 WARN]:        at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:143)
[11:27:31 WARN]:        at java.util.Map.computeIfAbsent(Map.java:957)
[11:27:31 WARN]:        at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:137)
[11:27:31 WARN]:        at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:143)
[11:27:31 WARN]:        at net.minecraft.server.v1_13_R2.ChunkStatus$1.a(SourceFile:53)
[11:27:31 WARN]:        at net.minecraft.server.v1_13_R2.ChunkStatus$1.a(SourceFile:27)
[11:27:31 WARN]:        at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:143)
[11:27:31 WARN]:        at java.util.Map.computeIfAbsent(Map.java:957)
[11:27:31 WARN]:        at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:137)
[11:27:31 WARN]:        at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:143)
[11:27:31 WARN]:        at net.minecraft.server.v1_13_R2.ChunkStatus.a(SourceFile:105)
[11:27:31 WARN]:        at net.minecraft.server.v1_13_R2.ChunkStatus.a(SourceFile:22)
[11:27:31 WARN]:        at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:143)
[11:27:31 WARN]:        at java.util.Map.computeIfAbsent(Map.java:957)
[11:27:31 WARN]:        at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:137)
[11:27:31 WARN]:        at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:143)
[11:27:31 WARN]:        at net.minecraft.server.v1_13_R2.ChunkStatus.a(SourceFile:105)
[11:27:31 WARN]:        at net.minecraft.server.v1_13_R2.ChunkStatus.a(SourceFile:22)
[11:27:31 WARN]:        at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:143)
[11:27:31 WARN]:        at java.util.Map.computeIfAbsent(Map.java:957)
[11:27:31 WARN]:        at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:137)
[11:27:31 WARN]:        at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:143)
[11:27:31 WARN]:        at net.minecraft.server.v1_13_R2.ChunkStatus.a(SourceFile:105)
[11:27:31 WARN]:        at net.minecraft.server.v1_13_R2.ChunkStatus.a(SourceFile:22)
[11:27:31 WARN]:        at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:143)
[11:27:31 WARN]:        at java.util.Map.computeIfAbsent(Map.java:957)
[11:27:31 WARN]:        at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:137)
[11:27:31 WARN]:        at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:115)
[11:27:31 WARN]:        at net.minecraft.server.v1_13_R2.Scheduler.a(SourceFile:61)
[11:27:31 WARN]:        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.
[11:27:31 WARN]:        at com.google.common.util.concurrent.MoreExecutors$DirectExecutorService.exe
[11:27:31 WARN]:        at java.util.concurrent.CompletableFuture.asyncSupplyStage(CompletableFuture
[11:27:31 WARN]:        at java.util.concurrent.CompletableFuture.supplyAsync(CompletableFuture.java
[11:27:31 WARN]:        at net.minecraft.server.v1_13_R2.Scheduler.a(SourceFile:62)
[11:27:31 WARN]:        at net.minecraft.server.v1_13_R2.SchedulerBatch.a(SourceFile:39)
[11:27:31 WARN]:        at net.minecraft.server.v1_13_R2.ChunkProviderServer.getChunkAt(ChunkProvide
[11:27:31 WARN]:        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.createWorld(CraftServer.java:
[11:27:31 WARN]:        at org.bukkit.Bukkit.createWorld(Bukkit.java:486)
[11:27:31 WARN]:        at org.bukkit.WorldCreator.createWorld(WorldCreator.java:279)
[11:27:31 WARN]:        at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.ja
[11:27:31 WARN]:        at com.onarandombox.MultiverseCore.utils.WorldManager.addWorld(WorldManager.
[11:27:31 WARN]:        at com.onarandombox.MultiverseCore.commands.CreateCommand.runCommand(CreateC
[11:27:31 WARN]:        at com.onarandombox.commandhandler.CommandHandler.checkAndRunCommand(Command
[11:27:31 WARN]:        at java.util.Map.computeIfAbsent(Map.java:957)
[11:27:31 WARN]:        at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:137)
[11:27:31 WARN]:        at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:115)
[11:27:31 WARN]:        at net.minecraft.server.v1_13_R2.Scheduler.a(SourceFile:61)
[11:27:31 WARN]:        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
[11:27:31 WARN]:        at com.google.common.util.concurrent.MoreExecutors$DirectExecutorService.execute(MoreExecutors.java:260)
[11:27:31 WARN]:        at java.util.concurrent.CompletableFuture.asyncSupplyStage(CompletableFuture.java:1604)
[11:27:31 WARN]:        at java.util.concurrent.CompletableFuture.supplyAsync(CompletableFuture.java:1830)
[11:27:31 WARN]:        at net.minecraft.server.v1_13_R2.Scheduler.a(SourceFile:62)
[11:27:31 WARN]:        at net.minecraft.server.v1_13_R2.SchedulerBatch.a(SourceFile:39)
[11:27:31 WARN]:        at net.minecraft.server.v1_13_R2.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:109)
[11:27:31 WARN]:        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.createWorld(CraftServer.java:991)
[11:27:31 WARN]:        at org.bukkit.Bukkit.createWorld(Bukkit.java:486)
[11:27:31 WARN]:        at org.bukkit.WorldCreator.createWorld(WorldCreator.java:279)
[11:27:31 WARN]:        at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:467)
[11:27:31 WARN]:        at com.onarandombox.MultiverseCore.utils.WorldManager.addWorld(WorldManager.java:269)
[11:27:31 WARN]:        at com.onarandombox.MultiverseCore.commands.CreateCommand.runCommand(CreateCommand.java:114)
[11:27:31 WARN]:        at com.onarandombox.commandhandler.CommandHandler.checkAndRunCommand(CommandHandler.java:279)
[11:27:31 WARN]:        at com.onarandombox.commandhandler.CommandHandler.processFoundCommands(CommandHandler.java:143)
[11:27:31 WARN]:        at com.onarandombox.commandhandler.CommandHandler.locateAndRunCommand(CommandHandler.java:93)
[11:27:31 WARN]:        at com.onarandombox.MultiverseCore.MultiverseCore.onCommand(MultiverseCore.java:908)
[11:27:31 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46)
[11:27:31 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[11:27:31 WARN]:        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:704)
[11:27:31 WARN]:        at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1621)
[11:27:31 WARN]:        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1461)
[11:27:31 WARN]:        at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45)
[11:27:31 WARN]:        at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:1)
[11:27:31 WARN]:        at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:9)
[11:27:31 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[11:27:31 WARN]:        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[11:27:31 WARN]:        at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199)
[11:27:31 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:896)
[11:27:31 WARN]:        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417)
[11:27:31 WARN]:        ... 3 more
[11:27:31 WARN]: Caused by: java.lang.UnsupportedOperationException: Custom generator is missing required method generateChunkData
[11:27:31 WARN]:        at org.bukkit.generator.ChunkGenerator.generateChunkData(ChunkGenerator.java:79)
[11:27:31 WARN]:        at org.bukkit.craftbukkit.v1_13_R2.generator.CustomChunkGenerator.createChunk(CustomChunkGenerator.java:61)
[11:27:31 WARN]:        at net.minecraft.server.v1_13_R2.ChunkTaskBase.a(SourceFile:13)
[11:27:31 WARN]:        at net.minecraft.server.v1_13_R2.ChunkTask.a(SourceFile:35)
[11:27:31 WARN]:        at net.minecraft.server.v1_13_R2.ChunkStatus.a(SourceFile:95)
[11:27:31 WARN]:        at net.minecraft.server.v1_13_R2.ChunkTaskScheduler.a(ChunkTaskScheduler.java:75)
[11:27:31 WARN]:        at net.minecraft.server.v1_13_R2.ChunkTaskScheduler.a(ChunkTaskScheduler.java:1)
[11:27:31 WARN]:        at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:147)
[11:27:31 WARN]:        at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
[11:27:31 WARN]:        ... 82 more
[11:27:31 INFO]: An internal error occurred when attempting to perform this command.
[11:27:31 INFO]: Details were printed to the server console and logs, please add that to your bug report.
```

**Comment by AirCraze** [comment]
The owner no longer replies. The plugin supports up to MC version 1.7-1.10
